# Generated by Django 2.2.3 on 2019-07-31 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mood.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mood', models.IntegerField(choices=[(mood.models.MoodChoice(1), 1), (mood.models.MoodChoice(2), 2), (mood.models.MoodChoice(3), 3)])),
                ('message', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
