# Generated by Django 2.2.3 on 2019-08-03 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True),
        ),
    ]
